language: python
env:
    global:
        # Set defaults to avoid repeating in most cases
        - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
        - NUMPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='six yaml dpath trollsift satpy'
        - PIP_DEPENDENCIES='posttroll'
        - SETUP_XVFB=False
        - EVENT_TYPE='push pull_request'
        - SETUP_CMD='test'
        - CONDA_CHANNELS='conda-forge'
        - CONDA_CHANNEL_PRIORITY='True'
matrix:
  include:
  - env: PYTHON_VERSION=2.7
    os: linux
  - env: PYTHON_VERSION=2.7
    os: osx
    language: generic
  - env: PYTHON_VERSION=3.6
    os: linux
  - env: PYTHON_VERSION=3.6
    os: osx
    language: generic
install:
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
script:
- coverage run --source=trollflow2 setup.py test
# TODO:
# - coverage run -a --source=satpy -m behave satpy/tests/features --tags=-download
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; codecov; fi
#notifications:
#  slack:
#    rooms:
#    - pytroll:96mNSYSI1dBjGyzVXkBT6qFt#github
